[workspace]

default-members = ["test-mobile"]
members = ["test-mobile", "test-mobile-game"]

resolver = "3"

[workspace.dependencies]
anyhow = "~1.0"
convert_case = "~0.10"
git2 = "~0.20"
structopt = "~0.3"
toml = "~0.8"
