[package]
name = "test-mobile"
version = "0.1.0"
edition = "2021"
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
description = "Mobile project generator for test-engine"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/vlasdasz/test-mobile"
repository = "https://github.com/vlasdasz/test-mobile"

[[bin]]
name = "test-mobile"


[dependencies]
