[package]
authors = ["Vladas Zakrevskis <146100@gmail.com>"]
edition = "2024"
name = "test-mobile-game"
version = "0.1.0"

[lib]
crate-type = ["rlib", "staticlib"]
name = "test_mobile_game"

[dependencies]
